name: Unit Test
on: [push]
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.4.0
      - name: Setup virtual envrionment
        run: $ python -m venv env
      - name: Activate virtual env
        run: $ . env/bin/activate
      - name: install required packages
        run: $ pip install -r requirements.txt
      - name: Run unit test
        run: $ pytest tests/
        
